### PR TITLE
Add support for quality data!

### PR DESCRIPTION
**Pull request by laceysanderson**
This PR adds support for importing and displaying quality information for LIMS sequencing runs.

### Data import
Quality data is associated with an existing sequencing run using the "LIMS Sample Quality Importer"
1. Update the module including running `update.php` (Already done on staging)
2. Ensure you have given yourself permission to see the importer (People > Permissions then check "Importer: Use the LIMS Sample Quality Importer"  (Already done on staging)
3. Go to Admin > Tripal > Data Loaders > LIMS Sample Quality Importer and create a file based on the details provided for the importer. Here's the one already imported into staging: [lims-test.txt](https://github.com/UofS-Pulse-Binfo/lims_rawseq/files/3912405/lims-test.txt)
4. You can check that data inserted properly using the "Devel" tab on an existing sequencing run (go to `$node->samples[0]->quality_info` for example) or by looking at the database (see table `lims_seqrun_samples_info`).

### Data Display
1. Import test data using instructions above.
2. Go to runs matching the following criteria (example in staging):
    - single sample, no quality information (node/1782785)
    - single sample, has quality information (node/1782795)
    - multi-sample, no quality information (node/1782743)
    - multi-sample, has quality information (node/1782744)

### CODE REVIEW

**Comment by ruobinLiu** [comment]
The quality statistics are a bit hard to read (without dash, unit etc...), other than this, it is perfect.

**Comment by carolyncaron** [comment]
I sadly couldn't get this to work fully on my local clone - I finished Steps 1-3 without any problems but the Raw Sequence Search table does not render properly. I also see multiple Missing handler messages, for example:
> Missing handler: lims_seqrun library_type field
> Missing handler: lims_seqrun index_type field
> Missing handler: lims_seqrun technology field

However, it's worth mentioning that my clone is seriously outdated... 😛 

When I test on staging, the examples appear as expected. I echo Ruobin's suggestion to format the numbers such that they are more readable. I am also on the fence about the bold red text in the Quality Statistics field. It feels like something is wrong (ie. the researcher may feel they completed the form incorrectly) when we may just not have that information yet.

**Comment by laceysanderson** [comment]
Numbers are now formatted with the typical comma's. I can't add units since I don't have that information. A good way to solve this would be to change our import file headers to include the units.

@carolyncaron is it just the search that's not working? That was covered by a previous PR but it sounds like you need to disable the old Drupal view which is overriding the new search functionality.

**Comment by carolyncaron** [comment]
Thanks @laceysanderson for helping me disable the view, it works perfectly now!

The styling tweaks look great and the new library type filter also works, so I think this PR is good to go! 👍

**Pull request merged**
